# Generated by Django 4.0.6 on 2022-08-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_rename_owner_pet_owner_id_alter_pet_owner_id'),
        ('walk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walk',
            old_name='pet',
            new_name='pet_id',
        ),
        migrations.AlterField(
            model_name='walk',
            name='pet_id',
            field=models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
